---
# Create commands specify empty directories to be created.
- create:
    - ~/.config/bat # bat config
    - ~/.config/bat/themes # bat themes
- link:
    ~/.config/bat/config:
      force: true
      path: config/bat/config
    ~/.config/bat/themes/:
      force: true
      glob: true
      path: config/bat/themes/*.tmTheme
- shell:
    - [bat cache --build, addings bat themes]
