---
# Create commands specify empty directories to be created.
- create:
    - ~/.config/bat  # bat config
    - ~/.config/bat/themes  # bat themes
- link:
    ~/.config/bat/config:
      force: true
      path: config/bat/config
    ~/.config/bat/themes/:
      glob: true
      path: config/bat/themes/*.tmTheme
      force: true
- shell:
    - [batcat cache --build, addings bat themes]
