# Create commands specify empty directories to be created.
- create:
      - ~/.config/topgrade # topgrade config
- link:
      ~/.config/topgrade/topgrade.toml:
          force: true
          path: config/topgrade/topgrade.toml
