[dotfiles]
"~/Library/Application Support/Code/User/keybindings.json" = { source = "~/.dotfiles/config/vscode/keybindings.json" }
"~/Library/Application Support/Code/User/settings.json" = { source = "~/.dotfiles/config/vscode/settings.common.json" }
