# Create commands specify empty directories to be created.
- create:
        - ~/.config/yazi # yazi config
- link:
        ~/.config/yazi/:
              glob: true
              force: true
              path: config/yazi/*.toml
- shell:
        - [command -v ya >/dev/null && cd ~/.config/yazi && ya pack -i || true, config yazi]
