# Create commands specify empty directories to be created.
- create:
    - ~/.config/yazi #yazi config

- link:
    ~/.config/yazi/:
      glob: true
      force: true
      path: config/yazi/*.toml

- shell:
    - [cd ~/.config/yazi && ya pack -i, config yazi]
