- create:
      - ~/.config/zellij # zellij config
      - ~/.config/zellij/layouts # zellij layouts
      - ~/.config/zellij/plugins # zellij layouts
- link:
      ~/.config/zellij/config.kdl:
          path: config/zellij/config.kdl
          force: true
      ~/.config/zellij/layouts/vibe.kdl:
          path: config/zellij/vibe.kdl
          force: true
      ~/.config/zellij/layouts/vibe.swap.kdl:
          path: config/zellij/vibe.swap.kdl
          force: true
- shell:
      - config/zellij/setup.sh
