- link:
    ~/.aliases:
      path: config/zsh/common/.aliases
    ~/.zsh_functions:
      path: config/zsh/functions/
    ~/.zshrc:
      force: true
      path: config/zsh/zshrc
    ~/.env:
      path: config/zsh/common/.env
