---
# dotbot base configuration
# https://github.com/anishathalye/dotbot

- defaults:
    link:
      relink: true
      create: true
      force: true

# Clean up dead symbolic links in common directories
- clean:
    - '~'
    - '~/.config'
    - '~/.local/bin'
