[settings]
dotfiles.root = "~/.dotfiles"
dotfiles.default_mode = "symlink"

[dotfiles]
"~/.aliases" = { source = "~/.dotfiles/config/zsh/common/.aliases" }
"~/.env.zsh" = { source = "~/.dotfiles/config/zsh/common/.env.zsh" }
"~/.zsh_functions" = { source = "~/.dotfiles/config/zsh/functions/" }
"~/.zshrc" = { source = "~/.dotfiles/config/zsh/zshrc" }
"~/.fzf.bash" = { source = "~/.dotfiles/config/fzf/.fzf.bash" }
"~/.fzf.zsh" = { source = "~/.dotfiles/config/fzf/.fzf.zsh" }
"~/.fzfrc" = { source = "~/.dotfiles/config/fzf/.fzfrc" }
"~/.config/atuin/config.toml" = { source = "~/.dotfiles/config/atuin/config.toml" }
"~/.config/bat/config" = { source = "~/.dotfiles/config/bat/config" }
"~/.bunfig.toml" = { source = "~/.dotfiles/config/bun/bunfig.toml" }
"~/.cargo/config.toml" = { source = "~/.dotfiles/config/cargo/config.toml" }
"~/.editorconfig" = { source = "~/.dotfiles/config/editorconfig/.editorconfig" }
"~/.config/eza/theme.yml" = { source = "~/.dotfiles/config/eza/catppuccin-mocha.yml" }
"~/.config/fastfetch/config.jsonc" = { source = "~/.dotfiles/config/fastfetch/config.jsonc" }
"~/.config/fastfetch/logos" = { source = "~/.dotfiles/config/fastfetch/logos" }
"~/.gitattributes" = { source = "~/.dotfiles/config/git/.gitattributes" }
"~/.gitconfig" = { source = "~/.dotfiles/config/git/.gitconfig" }
"~/.gitignore" = { source = "~/.dotfiles/config/git/.gitignore" }
"~/.config/lazygit/config.yml" = { source = "~/.dotfiles/config/lazygit/config.yml" }
"~/.lessfilter" = { source = "~/.dotfiles/config/lesspipe/lessfilter" }
"~/.config/mise/config.toml" = { source = "~/.dotfiles/config/mise/config.toml" }
"~/.config/nvim/lua/plugins/user-plugins.lua" = { source = "~/.dotfiles/config/nvim/user-plugins.lua" }
"~/.config/tealdeer/config.toml" = { source = "~/.dotfiles/config/tealdeer/config.toml" }
"~/.config/topgrade/topgrade.toml" = { source = "~/.dotfiles/config/topgrade/topgrade.toml" }
"~/.config/uv/uv.toml" = { source = "~/.dotfiles/config/uv/uv.toml" }
"~/.vscode-server/data/Machine/settings.json" = { source = "~/.dotfiles/vscode/settings_server.json" }
"~/.config/yazi/package.toml" = { source = "~/.dotfiles/config/yazi/package.toml" }
"~/.config/yazi/theme.toml" = { source = "~/.dotfiles/config/yazi/theme.toml" }
"~/.config/yazi/yazi.toml" = { source = "~/.dotfiles/config/yazi/yazi.toml" }
"~/.config/zellij/config.kdl" = { source = "~/.dotfiles/config/zellij/config.kdl" }
"~/.config/zellij/layouts/vibe.kdl" = { source = "~/.dotfiles/config/zellij/vibe.kdl" }
"~/.config/zellij/layouts/vibe.swap.kdl" = { source = "~/.dotfiles/config/zellij/vibe.swap.kdl" }
"~/.config/herdr/config.toml" = { source = "~/.dotfiles/config/herdr/config.toml" }
