[misc]

# Disable specific steps - same options as the command line flag
disable = [
    "containers",
    # Managed by mise
    "bun",
    "pipx",
    "uv",
    "rustup",
    "pip3",
    "node",
    "yarn",
    # Disabled
    "git_repos",
    "yazi",
]

# Cleanup temporary or old files (default: false)
cleanup = true

[git]
# How many repos to pull or fetch at max in parallel
# max_concurrency = 5

# Additional git repositories to pull or fetch
repos = [
    "~/code/clones/managed/*/",
]

# Set to `false` to skip pulling/fetching the predefined git repos
# pull_predefined = false

# Arguments to pass Git when pulling/fetching Repositories
# arguments = "--rebase --autostash"

# Whether to perform a `git fetch` instead of `git pull`
# fetch_only = false
