# Create commands specify empty directories to be created.
- create:
    - ~/.config # configuration files
    - ~/dev/code/projects # my projects
    - ~/dev/code/clones # read-only git clones
    - ~/dev/code/Templates # read-only projects boilerplates
    - ~/dev/code/Workspaces # code-station to try new stuff
