- link:
    ~/Appdata/Roaming/bat/config:
      create: true
      path: config/bat/config
    ~/Appdata/Roaming/bat.config/themes/:
      create: true
      glob: true
      path: config/bat/themes/*.tmTheme

- shell:
    - [bat cache --build, addings bat themes]
