- link:
    ~/.gitignore:
      force: true
      path: git/.gitignore
    ~/.gitconfig:
      force: true
      path: git/.gitconfig
    ~/.gitconfig.local:
      path: git/windows/.gitconfig.local
    ~/.gitattributes:
      force: true
      path: git/.gitattributes
