general.import = [
    "~/.config/alacritty/appearance.toml",
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"
ZSH_TMUX_AUTOSTART=true

# copy to clipboard on mouse selection
[selection]
save_to_clipboard = true
