#
# Appearance
#

[window]
# windows.opacity since version 0.10.0
opacity = 0.95

[window.dimensions]
columns = 140
lines = 48

[window.padding]
x=10
y=10

#
# Fonts
#

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
