## 🕒 Atuin Configuration
## https://docs.atuin.sh/configuration/config/

# --- Sync ---
auto_sync = true
update_check = true

# --- Appearance ---
# Available styles: "full", "compact"
style = "full"
inline_height = 0
show_preview = true
inline_height_shell_up_key_binding = 15


# --- Search ---
# Available modes: "prefix", "fulltext", "fuzzy", "skims"
search_mode = "fuzzy"

# --- Filter ---
# Default filter mode: "global", "host", "session", "directory"
filter_mode = "global"
filter_mode_shell_up_key_binding = "directory"
