#!/usr/bin/env lua

local user = os.getenv("USER")
local home = os.getenv("HOME")
local sbar_lua_path = home .. "/.local/share/sketchybar_lua"

-- 1. 自动安装/更新 SbarLua 模块 (仅在不存在时执行)
local handle = io.open(sbar_lua_path .. "/sketchybar.so", "r")
if not handle then
    print("SbarLua not found, installing...")
    os.execute("git clone https://github.com/FelixKratz/SbarLua.git /tmp/SbarLua && cd /tmp/SbarLua/ && make install && rm -rf /tmp/SbarLua/")
else
    handle:close()
end

-- 2. 动态配置 package.cpath 和 path
package.cpath = package.cpath .. ";" .. sbar_lua_path .. "/?.so"

local lua_version = _VERSION:match("%d%.%d")
package.path = package.path .. ";" .. home .. "/.luarocks/share/lua/" .. lua_version .. "/?.lua;" .. home .. "/.luarocks/share/lua/" .. lua_version .. "/?/init.lua"
package.cpath = package.cpath .. ";" .. home .. "/.luarocks/lib/lua/" .. lua_version .. "/?.so"

-- 3. 加载核心模块
sbar = require("sketchybar")

sbar.begin_config()
require("init")
sbar.hotload(true)
sbar.end_config()

sbar.event_loop()
