[settings]
idiomatic_version_file_enable_tools = ["python"]

[tools]
bun = "latest"
just = "latest"
node = "lts"
pnpm = "latest"
yarn = "latest"
python = { version = "3.14", postinstall = "pip install --user pipx" }
uv = "latest"
rust = "stable"
"cargo:sd" = "latest"
"cargo:tealdeer" = "latest"
"cargo:topgrade" = "latest"
"cargo:xh" = "latest"
"cargo:zoxide" = "latest"
"cargo:bottom" = "latest"
"pipx:pre-commit" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
