[settings]
idiomatic_version_file_enable_tools = ["python", "node", "rust"]

[env]
PYTHON_PIP_VERSION = "latest"

[tools]
bun = "latest"
just = "latest"
node = "lts"
pnpm = "latest"
yarn = "latest"
go = "latest"
python = { version = "3.14", postinstall = "pip install --user pipx" }
uv = "latest"
rust = "stable"
"cargo:sd" = "latest"
"cargo:tealdeer" = "latest"
"cargo:topgrade" = "latest"
"cargo:xh" = "latest"
"cargo:zoxide" = "latest"
"cargo:bottom" = "latest"
"pipx:pre-commit" = "latest"
"pipx:thefuck" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"cargo:pay-respects" = "latest"
"pipx:trash-cli" = "latest"
"pipx:rich-cli" = "latest"
