name: Release

on:
  push:
    branches:
      - "develope"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Create Release Pull Request or Publish to GitHub
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects a script in package.json named "version"
          version: bun run version
          commit: 'chore: update versions and changelog'
          title: 'chore: update versions and changelog'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
